# Generated by Django 5.0.7 on 2024-07-21 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=100)),
                ('audio_file', models.FileField(upload_to='songs/')),
                ('album_art_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
